#!/usr/bin/env bash

run() {
	if ! pgrep -f $1; then
		$@&
	fi
}

nitrogen --restore
run dunst
run picom
run $HOME/.config/bspwm/polybar/launch.sh
# xset s off
# xset -dpms
xbacklight -set 85
xsetroot -cursor_name left_ptr

