#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		      "#2D2F31"
bspc config focused_border_color	      "#2DE72B"
bspc config presel_feedback_color	      "#2DE72B"

bspc rule -a Firefox desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart
