#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

bspc monitor -d 1 2 3 4

bspc config border_width                  2
bspc config window_gap                    8
bspc config top_padding                   0
bspc config bottom_padding                30
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color    "#2D2F31"
bspc config active_border_color    "#2D2F31"
bspc config focused_border_color   "#2DE72B"
bspc config presel_feedback_color  "#2DE72B"
bspc config urgent_border_color    "#FF0000"

bspc rule -a mpv state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Nsxiv state=floating
bspc rule -a Wrapper-2.0 state=floating border=off focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart
