#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d terminal web games mail

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		      "#2D2F31"
bspc config active_border_color	          "#2D2F31"
bspc config focused_border_color	      "#2DE72B"
bspc config presel_feedback_color	      "#2DE72B"
bspc config urgent_border_color 	      "#ff0000"

# bspc rule -a Gimp-2.10 desktop='^3' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Pcmanfm state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart.sh
